name: build-ubuntu

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      # allow opam depext to yes package manager prompts
      OPAMCONFIRMLEVEL: unsafe-yes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Just to build so we remove `·git` to prevent opam from checking out submodueles
      - name: Remove .git
        run: rm -rf .git

      - name: Setup OCaml 5.3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true

      - name: Install dependencies
        run: opam install -y . --deps-only --with-test --with-dev-setup --with-doc

      - name: Build
        run: opam exec -- dune build @all

      - name: Test
        run: opam exec -- dune runtest
